apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      name: back
  template:
    metadata:
      labels:
        name: back
    spec:
      containers:
        - name: backfoot
          image: armcool004/backapptest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
spec:
  selector:
    name: back
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080


